<!doctype html><html><head><meta charset="utf-8"><style>
@page{margin:48px 52px 58px}body{font-family:DejaVu Sans,sans-serif;color:#171717;font-size:9.4px;line-height:1.42}header{border-top:5px solid #111;border-bottom:1px solid #111;margin-bottom:18px;padding:13px 0 14px}.identity{border-collapse:collapse;width:100%;margin:0}.identity td{padding:0;border:0;vertical-align:top}.brand{font-size:9px;font-weight:bold;letter-spacing:1.2px;text-transform:uppercase}.legal{font-size:7.8px;margin-top:2px;color:#4a4a4a}.document-meta{text-align:right;font-size:8px;line-height:1.45;color:#333}header h1{font-size:22px;line-height:1.15;margin:18px 0 10px;font-weight:bold}.summary{border-top:1px solid #b7b7b7;padding-top:8px;font-size:8px}.summary strong{font-size:7px;letter-spacing:.5px;text-transform:uppercase}.summary .separator{padding:0 7px;color:#777}.content{counter-reset:section}.content h1:first-child{display:none}.content h1:first-child+p{display:none}.content h2{counter-increment:section;font-size:11px;line-height:1.25;margin:14px 0 7px;padding-top:6px;border-top:1.5px solid #111;page-break-after:avoid}.content h2:before{content:counter(section, decimal-leading-zero) "  ";font-size:8px;letter-spacing:.7px}.content h3{font-size:9.5px;margin:12px 0 5px;page-break-after:avoid}.content p{margin:5px 0;orphans:3;widows:3}.content p strong:first-child{font-size:8px}.content ul,.content ol{margin:5px 0 7px 18px;padding:0}.content li{margin:3px 0}.page-break{page-break-before:always}.content table{border-collapse:collapse;width:100%;font-size:8.4px;margin:9px 0 11px;table-layout:fixed}.content th{background:#efefed;color:#111;font-weight:bold;border-bottom:1.5px solid #111}.content td,.content th{padding:6px 7px;border:1px solid #888;vertical-align:top;word-wrap:break-word}.content tr{page-break-inside:avoid}.content thead{display:table-header-group}.content blockquote{border-left:2px solid #111;margin:10px 0;padding:2px 0 2px 10px}.unfilled{color:#000;border:1px dashed #555;padding:1px 3px}.footer{position:fixed;bottom:-30px;font-size:7px;color:#4a4a4a;border-top:1px solid #aaa;padding-top:5px;width:100%}.draft{color:#000;font-weight:bold;border:1px solid #000;display:inline-block;padding:3px 7px;margin-top:8px;font-size:7.5px;letter-spacing:.4px}
</style></head><body>
@php($snapshot = $version->snapshot ?? [])
@php($provider = $snapshot['provider'] ?? [])
@php($buyer = $snapshot['company'] ?? [])
<div class="footer">{{ $snapshot['document_number'] ?? 'Document' }} / Version {{ $version->version }} / Secure portal record</div>
<header><table class="identity"><tr><td><div class="brand">{{ ($provider['brand_name'] ?? null) ?: 'Ikira Company' }}</div><div class="legal">{{ $provider['legal_name'] ?? 'Service provider' }}</div></td><td class="document-meta"><strong>{{ $snapshot['document_number'] ?? $document->document_number }}</strong><br>Version {{ $version->version }}<br>{{ $version->created_at->format('F j, Y') }}</td></tr></table><h1>{{ $snapshot['title'] ?? $document->title }}</h1><div class="summary"><strong>Client</strong> {{ $buyer['billing_name'] ?? $buyer['name'] ?? $document->company->name }}<span class="separator">/</span><strong>Project</strong> {{ $snapshot['project']['name'] ?? $document->project?->name ?? 'General services' }}<span class="separator">/</span><strong>Status</strong> {{ $version->published_at ? str($document->status)->replace('_', ' ')->title() : 'Draft' }}</div>@unless($version->published_at)<div class="draft">DRAFT - REVIEW BEFORE SENDING</div>@endunless</header>
<div class="content">{!! app(\App\Services\DocumentHtmlService::class)->clean($version->content) !!}</div>
</body></html>
