<x-layouts.app title="Create invoice - Ikira Portal">
    <div class="mb-7"><h1 class="text-3xl font-semibold">Create invoice</h1><p class="mt-2 text-slate-500">Provider details are copied into a snapshot. Sending freezes the issued PDF; payments stay in the separate ledger.</p></div>
    @if($profile->missing(true))<div class="mb-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Provider / bank settings are incomplete. Drafts are allowed; sending requires the owner's confirmed details.</div>@endif
    <form method="GET" action="{{ route('owner.invoices.create') }}" class="mb-6 grid max-w-4xl gap-4 rounded-2xl border border-slate-200 bg-white p-5 md:grid-cols-3">
        <label class="text-sm font-medium">Milestone<select name="kind" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5">@foreach(['standard'=>'Custom / recurring','advance'=>'Advance','final'=>'Final milestone'] as $value=>$label)<option value="{{ $value }}" @selected($kind===$value)>{{ $label }}</option>@endforeach</select></label>
        <label class="text-sm font-medium">Accepted Project Services Agreement<select name="sow_document_id" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"><option value="">None</option>@foreach($sows as $sow)<option value="{{ $sow->id }}" @selected($selectedSow?->id === $sow->id)>{{ $sow->document_number ?: $sow->title }} / {{ $sow->company->name }}</option>@endforeach</select></label>
        <button class="self-end rounded-lg bg-slate-900 px-4 py-2.5 text-sm text-white">Load milestone defaults</button>
    </form>
    <form method="POST" action="{{ route('owner.invoices.store') }}" class="max-w-4xl space-y-5 rounded-2xl border border-slate-200 bg-white p-6">@csrf
        <input type="hidden" name="kind" value="{{ $kind }}"><input type="hidden" name="sow_document_id" value="{{ $selectedSow?->id }}">
        <p class="text-sm font-medium">{{ str($kind)->headline() }} invoice{{ $selectedSow ? ' / '.$selectedSow->document_number : '' }}</p>
        <div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium">Client<select name="company_id" required class="mt-1 w-full rounded-lg border border-slate-300 p-2.5">@foreach($companies as $company)<option value="{{ $company->id }}" @selected((int) old('company_id',$selectedSow?->company_id) === $company->id)>{{ $company->name }}</option>@endforeach</select></label><label class="text-sm font-medium">Project<select name="project_id" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"><option value="">None</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected((int) old('project_id',$selectedSow?->project_id) === $project->id)>{{ $project->company->name }} / {{ $project->name }}</option>@endforeach</select></label></div>
        @if($kind === 'final')<label class="block text-sm font-medium">Explicit delivery acceptance<select name="acceptance_document_id" required class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"><option value="">Select accepted delivery</option>@foreach($acceptances->where('parent_document_id',$selectedSow?->id) as $acceptance)<option value="{{ $acceptance->id }}" @selected((int) old('acceptance_document_id') === $acceptance->id)>{{ $acceptance->document_number }} / {{ $acceptance->title }}</option>@endforeach</select></label>@endif
        <div class="grid gap-4 sm:grid-cols-3"><label class="text-sm font-medium">Issue date<input type="date" name="issue_date" value="{{ old('issue_date',today()->format('Y-m-d')) }}" required class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"></label><label class="text-sm font-medium">Due date<input type="date" name="due_date" value="{{ old('due_date',today()->addDays((int)($profile->details['payment_due_days'] ?? 7))->format('Y-m-d')) }}" required class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"></label><label class="text-sm font-medium">Currency<select name="currency" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5">@foreach(['USD','EUR','MDL'] as $currency)<option @selected(old('currency',$selectedSow ? 'USD' : ($profile->details['currency'] ?? 'USD'))===$currency)>{{ $currency }}</option>@endforeach</select></label></div>
        <h2 class="font-semibold">Items</h2><p class="text-xs text-slate-500">Milestone amounts are suggestions, not tax calculations. Final suggestions subtract prior invoices, not just payments. Sending checks against the confirmed project total.</p>
        @for($i=0;$i<4;$i++)<div class="grid gap-3 sm:grid-cols-[1fr_110px_160px]"><label class="text-xs">Description<input name="items[{{ $i }}][description]" value="{{ old('items.'.$i.'.description', $i===0 && $selectedSow ? str($kind)->headline().' milestone - '.$selectedSow->document_number : '') }}" {{ $i?'':'required' }} class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"></label><label class="text-xs">Quantity<input type="number" step="0.01" min="0.01" name="items[{{ $i }}][quantity]" value="{{ old('items.'.$i.'.quantity',1) }}" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"></label><label class="text-xs">Unit price<input type="number" step="0.01" min="0" name="items[{{ $i }}][unit_price]" value="{{ old('items.'.$i.'.unit_price',$i===0 ? $suggestedAmount : '') }}" {{ $i?'':'required' }} class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"></label></div>@endfor
        <div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium">Discount<input type="number" step="0.01" min="0" name="discount" value="{{ old('discount',0) }}" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"></label><label class="text-sm font-medium">Tax amount<input type="number" step="0.01" min="0" name="tax_amount" value="{{ old('tax_amount',0) }}" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"></label></div>
        <label class="block text-sm font-medium">Verified tax treatment / rate or applicable reason none is charged<textarea name="tax_description" rows="2" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5">{{ old('tax_description',$profile->details['tax_note'] ?? '') }}</textarea></label>
        <label class="block text-sm font-medium">Payment instructions<textarea name="payment_instructions" rows="6" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5">{{ old('payment_instructions',$profile->paymentInstructions()) }}</textarea></label>
        <label class="block text-sm font-medium">Client notes<textarea name="public_notes" rows="3" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5">{{ old('public_notes') }}</textarea></label>
        <button class="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-medium text-white">Create draft</button>
    </form>
</x-layouts.app>
