<x-layouts.app title="New invoice — Ikira Client Portal">
    <div class="mb-7"><h1 class="text-3xl font-semibold">Create invoice</h1></div>
    <form method="POST" action="{{ route('owner.invoices.store') }}" class="max-w-4xl space-y-5 rounded-2xl border border-slate-200 bg-white p-6">@csrf
        <div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium">Company<select name="company_id" required class="mt-1 w-full rounded-lg border border-slate-300 p-2.5">@foreach($companies as $company)<option value="{{ $company->id }}">{{ $company->name }}</option>@endforeach</select></label><label class="text-sm font-medium">Project<select name="project_id" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"><option value="">None</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->company->name }} — {{ $project->name }}</option>@endforeach</select></label></div>
        <div class="grid gap-4 sm:grid-cols-3"><label class="text-sm font-medium">Issue date<input type="date" name="issue_date" value="{{ today()->format('Y-m-d') }}" required class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"></label><label class="text-sm font-medium">Due date<input type="date" name="due_date" value="{{ today()->addDays(14)->format('Y-m-d') }}" required class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"></label><label class="text-sm font-medium">Currency<select name="currency" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5">@foreach(['USD','EUR','MDL'] as $currency)<option>{{ $currency }}</option>@endforeach</select></label></div>
        <h2 class="font-semibold">Items</h2>@for($i=0;$i<4;$i++)<div class="grid gap-3 sm:grid-cols-[1fr_110px_160px]"><input name="items[{{ $i }}][description]" placeholder="{{ $i ? 'Optional item' : 'Service description' }}" {{ $i?'':'required' }} class="rounded-lg border border-slate-300 p-2.5"><input type="number" step="0.01" min="0.01" name="items[{{ $i }}][quantity]" value="1" class="rounded-lg border border-slate-300 p-2.5"><input type="number" step="0.01" min="0" name="items[{{ $i }}][unit_price]" placeholder="Unit price" {{ $i?'':'required' }} class="rounded-lg border border-slate-300 p-2.5"></div>@endfor
        <div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium">Discount<input type="number" step="0.01" min="0" name="discount" value="0" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"></label><label class="text-sm font-medium">Payment instructions<textarea name="payment_instructions" rows="3" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"></textarea></label></div><label class="block text-sm font-medium">Client notes<textarea name="public_notes" rows="3" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"></textarea></label>
        <button class="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-medium text-white">Create draft</button>
    </form>
</x-layouts.app>
