<x-layouts.app title="New document — Ikira Client Portal">
    <div class="mb-7"><h1 class="text-3xl font-semibold">Create document</h1><p class="mt-1 text-slate-500">Template variables are replaced once and stored in an immutable version.</p></div>
    <form method="POST" action="{{ route('owner.documents.store') }}" class="max-w-4xl space-y-5 rounded-2xl border border-slate-200 bg-white p-6">@csrf
        <div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium">Company<select name="company_id" required class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"><option value="">Select</option>@foreach($companies as $company)<option value="{{ $company->id }}">{{ $company->name }}</option>@endforeach</select></label><label class="text-sm font-medium">Project<select name="project_id" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"><option value="">None</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->company->name }} — {{ $project->name }}</option>@endforeach</select></label></div>
        <div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium">Type<select name="type" required class="mt-1 w-full rounded-lg border border-slate-300 p-2.5">@foreach($types as $type)<option value="{{ $type }}">{{ str($type)->replace('_',' ')->title() }}</option>@endforeach</select></label><label class="text-sm font-medium">Template<select name="document_template_id" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"><option value="">Custom content</option>@foreach($templates as $template)<option value="{{ $template->id }}">{{ $template->name }}</option>@endforeach</select></label></div>
        <label class="block text-sm font-medium">Title<input name="title" value="{{ old('title') }}" required class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"></label>
        <label class="block text-sm font-medium">Expiration date<input type="date" name="expires_at" value="{{ old('expires_at') }}" class="mt-1 w-full rounded-lg border border-slate-300 p-2.5"></label>
        <label class="block text-sm font-medium">Custom HTML content<textarea name="content" rows="14" class="mt-1 w-full rounded-lg border border-slate-300 p-3 font-mono text-sm" placeholder="Leave blank when using a template">{{ old('content') }}</textarea></label>
        <p class="text-xs text-slate-500">Variables: @{{company.name}}, @{{contact.name}}, @{{project.name}}, @{{project.scope}}, @{{project.price}}, @{{today}}</p>
        <button class="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-medium text-white">Create draft</button>
    </form>
</x-layouts.app>
