<x-layouts.app :title="$document->title.' - Ikira Portal'">
    @php($isCurrent = $currentVersion->version === $document->current_version)
    <div class="mb-7 flex flex-wrap justify-between gap-4"><div><p class="text-sm font-medium text-indigo-600">{{ $document->document_number }} · Version {{ $currentVersion->version }}</p><h1 class="mt-1 text-3xl font-semibold">{{ $currentVersion->snapshot['title'] ?? $document->title }}</h1><p class="mt-2 text-slate-500">{{ $document->company->name }} · Current status: {{ str($document->status)->replace('_',' ')->title() }}</p></div><div class="flex flex-wrap items-start gap-2"><a href="{{ route('owner.documents.pdf', ['document'=>$document, 'version'=>$currentVersion->version]) }}" class="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm">Download this PDF</a>@if($document->status === 'draft' && $isCurrent)<form method="POST" action="{{ route('owner.documents.send', $document) }}">@csrf<input type="hidden" name="version" value="{{ $currentVersion->version }}"><button class="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm text-white">Send to client</button></form>@endif</div></div>
    @unless($isCurrent)<div class="mb-5 rounded-xl bg-indigo-50 p-4 text-sm">Viewing historical version {{ $currentVersion->version }}. <a class="text-indigo-600 underline" href="{{ route('owner.documents.show', $document) }}">Return to current draft / version</a></div>@endunless
    @if($isCurrent && !empty($currentVersion->snapshot['missing_fields']))<div class="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Draft needs {{ count($currentVersion->snapshot['missing_fields']) }} fields.</strong> Use Edit details to complete the highlighted values before sending.</div>@endif
    <div class="grid gap-6 xl:grid-cols-[1fr_320px]"><div class="space-y-6">
        <section class="overflow-x-auto rounded-2xl border border-slate-200 bg-white p-3 sm:p-6"><div class="document-preview">{!! app(\App\Services\DocumentHtmlService::class)->clean($currentVersion->content) !!}</div></section>
        @if($currentVersion->snapshot['minor_items'] ?? null)<section class="rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 class="font-semibold">Provider-agreed minor items</h2><p class="mt-2 whitespace-pre-wrap text-sm">{{ $currentVersion->snapshot['minor_items'] }}</p></section>@endif
        @if($document->pack_template)<a href="{{ route('owner.document-pack.edit', $document) }}" class="inline-block rounded-xl bg-slate-900 px-5 py-3 text-sm text-white">Edit details / create new version</a>
        @else<section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="font-semibold">Create a new version</h2><form method="POST" action="{{ route('owner.documents.update', $document) }}" class="mt-4 space-y-3">@csrf @method('PUT')<input type="hidden" name="base_version" value="{{ $document->current_version }}"><input name="title" value="{{ $document->title }}" required class="w-full rounded-lg border border-slate-300 p-2.5"><textarea name="content" rows="12" required class="w-full rounded-lg border border-slate-300 p-3 font-mono text-sm">{{ $currentVersion->content }}</textarea><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white">Save new version</button></form></section>@endif
    </div><aside class="space-y-5">
        <section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="font-semibold">Version history</h2><p class="mt-2 text-xs text-slate-500">Issued PDFs and signed uploads stay linked to their original version.</p><div class="mt-4 space-y-4 text-sm">@foreach($document->versions as $version)<div><a class="font-medium text-indigo-600" href="{{ route('owner.documents.show', ['document'=>$document, 'version'=>$version->version]) }}">Version {{ $version->version }}</a> · {{ $version->published_at ? 'Published' : 'Draft' }} @if($version->signed_at) · Signed @endif<p class="text-xs text-slate-500">{{ $version->created_at->format('M j, Y H:i') }}</p>@foreach($version->signedAttachments as $attachment)<a class="mt-1 block break-all text-indigo-600 underline" href="{{ route('attachments.download', $attachment) }}">Signed upload: {{ $attachment->original_name }}</a>@endforeach</div>@endforeach</div></section>
        @if($isCurrent && $document->requiresSignature() && in_array($document->status, ['awaiting_signature','signature_received']))<section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="font-semibold">Executed PDF</h2><p class="mt-2 text-xs text-slate-500">Confirm all required signatures and consents. A client upload is not automatically marked fully signed.</p><form method="POST" enctype="multipart/form-data" action="{{ route('owner.documents.signed', $document) }}" class="mt-4 space-y-3">@csrf<input type="hidden" name="version" value="{{ $currentVersion->version }}"><input type="file" name="file" accept="application/pdf" required class="block w-full text-sm"><label class="flex gap-2 text-xs"><input type="checkbox" name="execution_confirmed" value="1" required><span>I checked the required execution and consents for this exact version.</span></label><button class="rounded-lg bg-slate-900 px-3 py-2 text-sm text-white">Save executed PDF</button></form>
        @if($document->status === 'signature_received')@foreach($currentVersion->signedAttachments as $attachment)<form method="POST" action="{{ route('owner.documents.confirm-signed', $document) }}" class="mt-5 border-t pt-4">@csrf<input type="hidden" name="version" value="{{ $currentVersion->version }}"><input type="hidden" name="attachment_id" value="{{ $attachment->id }}"><p class="break-all text-xs">{{ $attachment->original_name }}</p><label class="mt-2 flex gap-2 text-xs"><input type="checkbox" name="execution_confirmed" value="1" required><span>This file has all required signatures / consents for this version.</span></label><button class="mt-3 text-sm font-medium text-indigo-600">Confirm this execution</button></form>@endforeach @endif</section>@endif
        <section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="font-semibold">Decisions</h2>@forelse($document->approvals as $approval)<div class="mt-4 text-sm"><p class="font-medium">{{ str($approval->decision)->replace('_',' ')->title() }} · v{{ $approval->version }}</p><p class="text-xs text-slate-500">{{ $approval->user?->name }} · {{ $approval->decided_at->format('M j, Y H:i') }}</p><p class="mt-1 whitespace-pre-wrap">{{ $approval->comment }}</p></div>@empty<p class="mt-3 text-sm text-slate-500">No decisions yet.</p>@endforelse</section>
        @foreach($document->attachments->whereNull('document_version_id') as $legacy)<a class="block text-sm text-indigo-600" href="{{ route('attachments.download', $legacy) }}">Legacy attachment (version not recorded): {{ $legacy->original_name }}</a>@endforeach
    </aside></div>
</x-layouts.app>
