<x-layouts.app :title="$document->title.' — Ikira Client Portal'">
    <div class="mb-7 flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm font-medium text-indigo-600">{{ str($document->type)->replace('_',' ')->title() }} · v{{ $document->current_version }}</p><h1 class="mt-1 text-3xl font-semibold">{{ $document->title }}</h1><p class="mt-1 text-slate-500">{{ $document->company->name }}{{ $document->project ? ' · '.$document->project->name : '' }}</p></div><div class="flex gap-2"><a href="{{ route('owner.documents.pdf', $document) }}" class="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-medium">Download PDF</a>@if($document->status==='draft')<form method="POST" action="{{ route('owner.documents.send', $document) }}">@csrf<button class="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-medium text-white">Send to client</button></form>@endif</div></div>
    <div class="grid gap-6 xl:grid-cols-[1fr_320px]"><div class="space-y-6"><section class="rounded-2xl border border-slate-200 bg-white p-6"><div class="prose max-w-none">{!! $currentVersion?->content !!}</div></section>
    <section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="font-semibold">Create new version</h2><p class="mt-1 text-sm text-slate-500">The existing version remains unchanged in history.</p><form method="POST" action="{{ route('owner.documents.update', $document) }}" class="mt-4 space-y-3">@csrf @method('PUT')<input name="title" value="{{ $document->title }}" required class="w-full rounded-lg border border-slate-300 p-2.5"><textarea name="content" rows="14" required class="w-full rounded-lg border border-slate-300 p-3 font-mono text-sm">{{ $currentVersion?->content }}</textarea><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white">Save as new version</button></form></section></div>
    <aside class="space-y-6"><section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="font-semibold">Status</h2><p class="mt-3 text-lg">{{ str($document->status)->replace('_',' ')->title() }}</p><dl class="mt-4 space-y-2 text-sm text-slate-500"><div>Sent: {{ $document->sent_at?->format('M j, Y H:i') ?? '—' }}</div><div>Viewed: {{ $document->viewed_at?->format('M j, Y H:i') ?? '—' }}</div><div>Accepted: {{ $document->accepted_at?->format('M j, Y H:i') ?? '—' }}</div></dl></section>
    @if($document->type==='contract')<section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="font-semibold">Signed contract</h2><form method="POST" enctype="multipart/form-data" action="{{ route('owner.documents.signed', $document) }}" class="mt-3">@csrf<input type="file" name="file" accept="application/pdf" required class="block w-full text-sm"><button class="mt-3 rounded-lg bg-slate-900 px-3 py-2 text-sm text-white">Upload signed PDF</button></form></section>@endif
    <section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="font-semibold">Version history</h2><div class="mt-3 space-y-3 text-sm">@foreach($document->versions as $version)<div><span class="font-medium">v{{ $version->version }}</span> · {{ $version->created_at->format('M j, Y H:i') }} @if($version->locked_at)<span class="text-emerald-600">Locked</span>@endif</div>@endforeach</div></section>
    <section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="font-semibold">Decisions</h2><div class="mt-3 space-y-3 text-sm">@forelse($document->approvals as $approval)<div><span class="font-medium">{{ str($approval->decision)->replace('_',' ')->title() }}</span> · v{{ $approval->version }}<p class="text-slate-500">{{ $approval->comment }}</p></div>@empty<p class="text-slate-500">No decisions yet.</p>@endforelse</div></section></aside></div>
</x-layouts.app>
