<x-layouts.app :title="$project->name.' — Ikira Client Portal'">
    <div class="mb-7 flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm font-medium text-indigo-600">{{ $project->company->name }}</p><h1 class="mt-1 text-3xl font-semibold">{{ $project->name }}</h1><p class="mt-1 text-slate-500">{{ str($project->type)->replace('_',' ')->title() }} · {{ str($project->status)->replace('_',' ')->title() }}</p></div><div class="flex items-center gap-4"><a href="{{ route('owner.payment-schedules.create', $project) }}" class="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-medium">Payment schedule</a><div class="text-right"><p class="text-3xl font-semibold">{{ $project->progress }}%</p><p class="text-sm text-slate-500">Project progress</p></div></div></div>
    @if($project->brief)@include('partials.brief-answers', ['brief' => $project->brief, 'class' => 'mb-6'])@endif
    <div class="grid gap-6 xl:grid-cols-[1fr_340px]">
        <section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="font-semibold">Workflow</h2><div class="mt-5 space-y-4">@forelse($project->stages as $stage)<form method="POST" action="{{ route('owner.projects.stages.update', [$project, $stage]) }}" class="grid gap-3 rounded-xl border border-slate-100 p-4 sm:grid-cols-[1fr_190px_220px_150px] sm:items-center">@csrf @method('PATCH')<div><p class="font-medium">{{ $stage->position }}. {{ $stage->title }}</p><p class="text-sm text-slate-500">{{ $stage->client_description }}</p></div><select name="status" class="rounded-lg border border-slate-300 px-2 py-2 text-sm">@foreach(['not_started','in_progress','approval_required','changes_requested','approved','completed','blocked'] as $status)<option value="{{ $status }}" @selected($stage->status === $status)>{{ str($status)->replace('_',' ')->title() }}</option>@endforeach</select><input name="override_reason" class="rounded-lg border border-slate-300 px-3 py-2 text-sm" placeholder="Reason if overriding approval"><button class="rounded-lg bg-slate-900 px-3 py-2 text-sm text-white">Update</button></form>@empty<p class="text-sm text-slate-500">No stages were added.</p>@endforelse</div></section>
        <div class="space-y-6"><section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="font-semibold">Project details</h2><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between gap-4"><dt class="text-slate-500">Budget</dt><dd>{{ $project->currency }} {{ number_format($project->price, 2) }}</dd></div><div class="flex justify-between gap-4"><dt class="text-slate-500">Target</dt><dd>{{ $project->target_completion_date?->format('M j, Y') ?? 'Not set' }}</dd></div><div><dt class="text-slate-500">Scope</dt><dd class="mt-1 whitespace-pre-line">{{ $project->scope ?: 'Not defined' }}</dd></div></dl></section>
        @if(auth()->user()->hasPermission('manage_work_items'))<section class="rounded-2xl border border-slate-200 bg-white p-5"><div class="flex items-center justify-between gap-3"><h2 class="font-semibold">Internal work items</h2><a href="{{ route('owner.work-items.create', ['project_id' => $project->id]) }}" class="text-sm text-indigo-600">Add</a></div><div class="mt-4 space-y-3">@forelse($project->workItems->whereNull('archived_at')->take(5) as $workItem)<a href="{{ route('owner.work-items.edit', $workItem) }}" class="block rounded-lg border border-slate-100 p-3"><p class="text-sm font-medium">{{ $workItem->title }}</p><p class="mt-1 text-xs text-slate-500">{{ \App\Models\WorkItem::STATUSES[$workItem->status] }} · {{ $workItem->assignee?->name ?? 'Unassigned' }}</p></a>@empty<p class="text-sm text-slate-500">No internal assignments.</p>@endforelse</div></section>@endif
        <section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="font-semibold">Client files</h2><div class="mt-4 space-y-2">@forelse($project->attachments as $attachment)<a class="block truncate text-sm text-indigo-600" href="{{ route('attachments.download', $attachment) }}">{{ $attachment->original_name }}</a>@empty<p class="text-sm text-slate-500">No files uploaded.</p>@endforelse</div><form method="POST" enctype="multipart/form-data" action="{{ route('owner.projects.attachments.store', $project) }}" class="mt-4">@csrf<input type="file" name="file" required class="block w-full text-sm"><button class="mt-3 rounded-lg bg-slate-900 px-3 py-2 text-sm text-white">Upload file</button></form></section></div>
    </div>
</x-layouts.app>
